In [1]:
import pandas as pd

In [2]:
pd.DataFrame({
    'yes':[50,21],
    "no": [37,57]
})

   yes  no
0   50  37
1   21  57

In [3]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [ ]:
series